/**
 * Product adapter: Release (+ liner notes) → canonical Document.
 * The PDF renderer never receives Release entities directly.
 */

import type { Document } from '@releaseflow/documents';
import { richTextToDocumentBlocks, type SourceRichText } from '@releaseflow/documents';
import type { RichTextDocument } from '@/lib/rich-text';
import { isRichTextEmpty } from '@/lib/rich-text';

export interface ReleaseDocumentInput {
  releaseTitle: string;
  primaryArtist: string;
  releaseType: string;
  releaseDate?: string | null;
  copyrightYear?: string | null;
  artworkUrl?: string | null;
  linerNotes: RichTextDocument | null;
}

function sanitizeFilenamePart(s: string): string {
  return (
    s
      .replace(/[<>:"/\\|?*]/g, '')
      .split('')
      .filter((ch) => ch.charCodeAt(0) >= 32)
      .join('')
      .replace(/\s+/g, ' ')
      .trim()
      .slice(0, 80) || 'Untitled'
  );
}

export function buildLinerNotesFilename(artist: string, title: string): string {
  return `${sanitizeFilenamePart(artist || 'Artist')} - ${sanitizeFilenamePart(title)} - Liner Notes.pdf`;
}

/**
 * Builds a canonical Document for liner-notes export.
 */
export function createReleaseLinerNotesDocument(input: ReleaseDocumentInput): Document {
  const metaLines = [
    input.releaseType,
    input.releaseDate,
    input.copyrightYear ? `© ${input.copyrightYear}` : null,
  ].filter(Boolean) as string[];

  const linerBlocks = !isRichTextEmpty(input.linerNotes)
    ? richTextToDocumentBlocks(input.linerNotes as SourceRichText)
    : [];

  return {
    title: input.releaseTitle,
    subtitle: input.primaryArtist,
    filename: buildLinerNotesFilename(input.primaryArtist, input.releaseTitle),
    cover: {
      imageUrl: input.artworkUrl ?? null,
      title: input.releaseTitle,
      subtitle: input.primaryArtist || undefined,
      lines: metaLines,
      generatedBy: 'Generated by ReleaseFlow',
    },
    metadata: {
      title: input.releaseTitle,
      author: 'ReleaseFlow',
      subject: 'Release Liner Notes',
      keywords: ['ReleaseFlow', 'Music', 'Liner Notes'],
      creator: 'ReleaseFlow',
    },
    header: {
      left: input.releaseTitle,
      right: input.primaryArtist || undefined,
    },
    footer: {
      left: 'Generated from ReleaseFlow',
    },
    sections: [
      {
        id: 'release-metadata',
        heading: 'Release',
        style: 'meta',
        blocks: [],
        metadataRows: [
          { label: 'Title', value: input.releaseTitle },
          ...(input.primaryArtist
            ? [{ label: 'Primary Artist', value: input.primaryArtist }]
            : []),
          ...(input.releaseType ? [{ label: 'Release Type', value: input.releaseType }] : []),
          ...(input.releaseDate ? [{ label: 'Release Date', value: input.releaseDate }] : []),
          ...(input.copyrightYear
            ? [{ label: 'Copyright Year', value: input.copyrightYear }]
            : []),
        ],
      },
      {
        id: 'liner-notes',
        heading: 'Liner Notes',
        style: 'body',
        blocks: linerBlocks,
      },
    ],
  };
}
